exclude: [CNAME, README.md, .gitignore]
favicon_log: '/assets/images/favicon/'
keywords:    "portfolio, jekyll, template, github, blog, single page, tech, html, css, javascript, personal website"
description: "Duc Nguyen's tech portfolio"

plugins:
    - jemoji   
emoji:
    src: "https://github.githubassets.com/images/icons/"